Use `ArrayBufferLike` instead of `ArrayBuffer` for reading/writing bytes
Prior to using `ArrayBufferLike`, TypeScript compilation errors in the generated output would occur:

```
src/generated/foobar.ts:1133:25 - error TS2345: Argument of type '(value: ArrayBuffer) => string' is not assignable to parameter of type 'StringLifter'.
  Types of parameters 'value' and 'bytes' are incompatible.
    Type 'Uint8Array<ArrayBufferLike>' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.
```

Unfortunately, due to merging #197, these legitimate errors were also hidden. Ideally, we should investigate
why the generated output has compilation issues and resolve them, and then revert #197.